import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from 'next/link'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Severe Storms Media</title>
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" referrerpolicy="no-referrer" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" type="image/png" href="/zeit.png" />
			</Head>


		<header className="bg-blue-600">
		  <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
			  <div className="w-full py-6 flex items-center justify-between border-b border-blue-500 lg:border-none">
				  <span className="sr-only">Severe Storms Media</span>
					<h2 className="font-bold text-gray-900">Severe Storms Media</h2>
				</div>
			</nav>
		</header>

			<footer className="bg-white">
				 <div className="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8"> 
				   <nav className="-mx-5 -my-2 flex flex-wrap justify-center">
					 <div className="px-5 py-2">
					 <Link href="/">
          <a className="text-base text-gray-500 hover:text-gray-900">Home</a>
        </Link>
					 </div>
					 </nav> 
				 </div>
			</footer>
		</div>
	)
}
